language: php

php:
    - 5.6
    - 5.5
    - 5.4

install:
    - composer self-update
    - composer install --no-interaction --prefer-source

before_script:
    - printf "\n" | pecl install judy

script: ./vendor/bin/phing test

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover ./test/report/coverage.clover
